version: 2

sources:
  - name: 'RAW_ADVENTURE_WORKS'
    description: "Tabelas Raw do Adventure Works"
    
    tables:
      - name: ADDRESS
      - name: COUNTRYREGION
      - name: PRODUCT
      - name: PRODUCTCATEGORY
      - name: PRODUCTLISTPRICEHISTORY
      - name: PRODUCTSUBCATEGORY
      - name: SALESORDERDETAIL
      - name: SALESORDERHEADER
      - name: SALESORDERHEADERSALESREASON
      - name: SALESREASON
      - name: STATEPROVINCE
      - name: PERSON
      - name: PERSONPHONE
      - name: EMAILADDRESS
      - name: PHONENUMBERTYPE
      - name: BUSINESSENTITYCONTACT
      - name: CUSTOMER
      - name: STORE
      - name: BUSINESSENTITY
      - name: CONTACTTYPE
      - name: CULTURE
      - name: ILLUSTRATION
      - name: PRODUCTDOCUMENT
      - name: PRODUCTINVENTORY
      - name: PRODUCTMODEL
      - name: PRODUCTMODELILLUSTRATION
      - name: PRODUCTMODELPRODUCTDESCRIPTIONCULTURE
      - name: PRODUCTPRODUCTPHOTO
      - name: PRODUCTVENDOR
      - name: SPECIALOFFERPRODUCT
      - name: TRANSACTIONHISTORY
      - name: TRANSACTIONHISTORYARCHIVE
      - name: PURCHASEORDERDETAIL
      - name: PERSONCREDITCARD
      - name: CREDITCARD
      - name: SALESTERRITORY
