with
    PRODUCTMODELPRODUCTDESCRIPTIONCULTURE as (
    select 
        PRODUCTMODELID
	    , PRODUCTDESCRIPTIONID
	    , cast(CULTUREID as VARCHAR) as FK_culture 
	    , cast(MODIFIEDDATE as date) as MODIFIEDDATE
    from {{ source('RAW_ADVENTURE_WORKS', 'PRODUCTMODELPRODUCTDESCRIPTIONCULTURE') }}
    )

select *
from PRODUCTMODELPRODUCTDESCRIPTIONCULTURE